### ISSUE TITLE
Invalid memory address when trying to use album art background.

### ISSUE THREAD

**Issue by jinithin** [aki237/gmus#1]
When invoking the following command:
`./gmus -fnt /usr/share/fonts/google-roboto/Roboto-Regular.ttf -dyn`

I get the following error:
```
[jonathan@fedora-home][Downloads]$ ./gmus -fnt /usr/share/fonts/google-roboto/Roboto-Regular.ttf -dyn
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5688c3]
goroutine 1 [running, locked to thread]:
main.imageBaseColor(0x0, 0x0, 0x5f68a0)
        /home/aki237/Desktop/gmus/image_base.go:12 +0x353
main.main()
        /home/aki237/Desktop/gmus/main.go:138 +0xa72
```

**Comment by aki237** [comment]
Thanks for the bug report. I'll look into it.

**Comment by aki237** [comment]
@R4WBIT Try now. I think it'll be fine

**Comment by jinithin** [comment]
Works great now. Thanks!
Is there anywhere I can put feature requests?

**Comment by aki237** [comment]
Open a new issue. I guess..
